'use strict'

let { callSpecs } = require('../../../../core/spec/callSpecs')
let { SpecBuilder } = require('../../../../core/spec/SpecBuilder')

let { testDOGFilters } = require('../../test/filters/testDOGFilters')
let { testDealerFilters } = require('../../test/filters/testDealerFilters')
let { testCustomersFilters } = require('../../test/filters/testCustomersFilters')
let { testUserFilters } = require('../../test/filters/testUserFilters')
let { testVehicleFilters } = require('../../test/filters/testVehicleFilters')
let { testOTASubscriptionFilters } = require('../../test/filters/testOTASubscriptionFilters')
let { testDeviceCollectionFilters } = require('../../test/filters/testDeviceCollectionFilters')
let { testDeviceFilters } = require('../../test/filters/testDeviceFilters')
let { testOEMFilters } = require('../../test/filters/testOEMFilters')
let { testRolesFilters } = require('../../test/filters/testRolesFilters')

describe(`Filters - Save, Edit, and Delete a Filter`, () => {

    const specDOG = SpecBuilder().setPortal(`Paccar Portal`)
                                            .setPortalType(`Staging`)
                                            .setName(`Filters - Save, Edit, and Delete a Filter - Dealer Owner Groups Table`)
                                            .setTestFunc(testDOGFilters)
                                            .setPassingRoles( [`peoplenetadmin`] )
                                            .build()

    const specDealer = SpecBuilder().setPortal(`Paccar Portal`)
                                            .setPortalType(`Staging`)
                                            .setName(`Filters - Save, Edit, and Delete a Filter - Dealers/Service Centers Table`)
                                            .setTestFunc(testDealerFilters)
                                            .setPassingRoles( [`peoplenetadmin`] )
                                            .build()

    const specCustomer = SpecBuilder().setPortal(`Paccar Portal`)
                                            .setPortalType(`Staging`)
                                            .setName(`Filters - Save, Edit, and Delete a Filter - Customers Table`)
                                            .setTestFunc(testCustomersFilters)
                                            .setPassingRoles( [`peoplenetadmin`] )
                                            .build()

    const specUser = SpecBuilder().setPortal(`Paccar Portal`)
                                            .setPortalType(`Staging`)
                                            .setName(`Filters - Save, Edit, and Delete a Filter - Users Table`)
                                            .setTestFunc(testUserFilters)
                                            .setPassingRoles( [`peoplenetadmin`] )
                                            .build()

    const specVehicle = SpecBuilder().setPortal(`Paccar Portal`)
                                            .setPortalType(`Staging`)
                                            .setName(`Filters - Save, Edit, and Delete a Filter - Vehicles Table`)
                                            .setTestFunc(testVehicleFilters)
                                            .setPassingRoles( [`peoplenetadmin`] )
                                            .build()

    const specOTASub = SpecBuilder().setPortal(`Paccar Portal`)
                                            .setPortalType(`Staging`)
                                            .setName(`Filters - Save, Edit, and Delete a Filter - OTA Subscriptions Table`)
                                            .setTestFunc(testOTASubscriptionFilters)
                                            .setPassingRoles( [`peoplenetadmin`] )
                                            .build()

    const specDeviceCol = SpecBuilder().setPortal(`Paccar Portal`)
                                            .setPortalType(`Staging`)
                                            .setName(`Filters - Save, Edit, and Delete a Filter - Device Collections Table`)
                                            .setTestFunc(testDeviceCollectionFilters)
                                            .setPassingRoles( [`peoplenetadmin`] )
                                            .build()

    const specDevice = SpecBuilder().setPortal(`Paccar Portal`)
                                            .setPortalType(`Staging`)
                                            .setName(`Filters - Save, Edit, and Delete a Filter - Devices Table`)
                                            .setTestFunc(testDeviceFilters)
                                            .setPassingRoles( [`peoplenetadmin`] )
                                            .build()

    const specOEM = SpecBuilder().setPortal(`Paccar Portal`)
                                            .setPortalType(`Staging`)
                                            .setName(`Filters - Save, Edit, and Delete a Filter - OEMs Table`)
                                            .setTestFunc(testOEMFilters)
                                            .setPassingRoles( [`peoplenetadmin`] )
                                            .build()

    const specRole = SpecBuilder().setPortal(`Paccar Portal`)
                                            .setPortalType(`Staging`)
                                            .setName(`Filters - Save, Edit, and Delete a Filter - Roles Table`)
                                            .setTestFunc(testRolesFilters)
                                            .setPassingRoles( [`otaTestAdmin`] )
                                            .build()

    callSpecs(specDOG)
    callSpecs(specDealer)
    callSpecs(specCustomer)
    callSpecs(specUser)
    callSpecs(specVehicle)
    callSpecs(specOTASub)
    callSpecs(specDeviceCol)
    callSpecs(specDevice)
    callSpecs(specOEM)
    callSpecs(specRole)
})